changelog:
  categories:
    - title: API Changes
      labels:
        - api
    - title: Front Changes
      labels:
        - front
    - title: Other Changes
      labels:
        - "*"
  dual_categories:
    - title: API and Front Changes
      labels:
        - api
        - front