name: Restrict pr api label
on:
  pull_request:
    branches:
      - develop
    paths:
      - apps/api/**

jobs:
  restrict-pr-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # APIディレクトリに変更がある場合は「api」ラベルを付ける
      - name: Add API label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              labels: ['api']
            })
